In [3]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(42)
prices = rng.integers(100, 5001, 20)
final_prices = prices * 1.18

print("Original prices:", prices)
print("First 5:", prices[:5])
print("Last 5:", prices[-5:])
print("Prices after 18% GST:", np.round(final_prices, 2))
print("Above Rs. 2500:", prices[prices > 2500])
print("Between Rs. 1000 and Rs. 3000:", prices[(prices >= 1000) & (prices <= 3000)])
print("Minimum:", prices.min(), "Maximum:", prices.max())
print("Mean:", prices.mean(), "Median:", np.median(prices))
print("Variance:", prices.var(), "Standard deviation:", prices.std())
print("Total value:", prices.sum())
print("Count above average:", np.sum(prices > prices.mean()))

pd.DataFrame({"Product_ID": np.arange(1, 21), "Original_Price": prices,
              "Final_Price_With_GST": np.round(final_prices, 2)}).to_csv("products.csv", index=False)
print("File saved successfully: products.csv")


Original prices: [ 537 3893 3308 2250 2222 4307  521 3517 1087  561 2680 4881 3705 3830
 3616 3952 2615  727 4215 2307]
First 5: [ 537 3893 3308 2250 2222]
Last 5: [3952 2615  727 4215 2307]
Prices after 18% GST: [ 633.66 4593.74 3903.44 2655.   2621.96 5082.26  614.78 4150.06 1282.66
  661.98 3162.4  5759.58 4371.9  4519.4  4266.88 4663.36 3085.7   857.86
 4973.7  2722.26]
Above Rs. 2500: [3893 3308 4307 3517 2680 4881 3705 3830 3616 3952 2615 4215]
Between Rs. 1000 and Rs. 3000: [2250 2222 1087 2680 2615 2307]
Minimum: 521 Maximum: 4881
Mean: 2736.55 Median: 2994.0
Variance: 1892554.5474999999 Standard deviation: 1375.7014747029966
Total value: 54731
Count above average: 10
File saved successfully: products.csv


In [4]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(42)
temperatures = rng.integers(20, 46, 30)

print("Original temperatures:", temperatures)
print("First 7 days:", temperatures[:7])
print("Day 10:", temperatures[9], "C")
print("Day 20:", temperatures[19], "C")
print("Above 35 C:", temperatures[temperatures > 35])
print("Between 25 C and 30 C:", temperatures[(temperatures >= 25) & (temperatures <= 30)])
print("Coolest:", temperatures.min(), "C | Hottest:", temperatures.max(), "C")
print("Average:", temperatures.mean(), "Median:", np.median(temperatures))
print("Variance:", temperatures.var(), "Standard deviation:", temperatures.std())
print("Days above monthly average:", np.sum(temperatures > temperatures.mean()))

pd.DataFrame({"Day": np.arange(1, 31), "Temperature_C": temperatures}).to_csv("temperature.csv", index=False)
print("File saved successfully: temperature.csv")

Original temperatures: [22 40 37 31 31 42 22 38 25 22 33 45 39 39 38 40 33 23 41 31 33 29 24 44
 40 36 30 41 34 31]
First 7 days: [22 40 37 31 31 42 22]
Day 10: 22 C
Day 20: 31 C
Above 35 C: [40 37 42 38 45 39 39 38 40 41 44 40 36 41]
Between 25 C and 30 C: [25 29 30]
Coolest: 22 C | Hottest: 45 C
Average: 33.8 Median: 33.5
Variance: 46.626666666666665 Standard deviation: 6.82837218278754
Days above monthly average: 15
File saved successfully: temperature.csv


In [5]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(42)
units = rng.integers(100, 801, 12)
bills = units * 6

print("Original consumption:", units)
print("First 3 months:", units[:3])
print("Last month:", units[-1])
print("Bills at Rs. 6 per unit:", bills)
print("Months above 500 units:", units[units > 500])
print("Minimum: Month", units.argmin() + 1, "=", units.min(), "units")
print("Maximum: Month", units.argmax() + 1, "=", units.max(), "units")
print("Total annual consumption:", units.sum())
print("Average:", units.mean(), "Variance:", units.var(), "Standard deviation:", units.std())
print("Months below average:", np.sum(units < units.mean()))

pd.DataFrame({"Month": np.arange(1, 13), "Consumption_Units": units,
              "Bill_Rs": bills}).to_csv("electricity.csv", index=False)
print("File saved successfully: electricity.csv")


Original consumption: [162 642 558 407 403 701 160 588 241 166 469 783]
First 3 months: [162 642 558]
Last month: 783
Bills at Rs. 6 per unit: [ 972 3852 3348 2442 2418 4206  960 3528 1446  996 2814 4698]
Months above 500 units: [642 558 701 588 783]
Minimum: Month 7 = 160 units
Maximum: Month 12 = 783 units
Total annual consumption: 5280
Average: 440.0 Variance: 44671.833333333336 Standard deviation: 211.35712274095079
Months below average: 6
File saved successfully: electricity.csv


In [6]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(42)
battery = rng.integers(5, 101, 20)

print("Original battery readings:", battery)
print("First:", battery[0], "Fifth:", battery[4], "Tenth:", battery[9], "Last:", battery[-1])
print("Below 20%:", battery[battery < 20])
print("Between 30% and 70%:", battery[(battery >= 30) & (battery <= 70)])
print("Average:", battery.mean())
print("Minimum:", battery.min(), "Maximum:", battery.max())
print("Variance:", battery.var(), "Standard deviation:", battery.std())
print("Readings below average:", np.sum(battery < battery.mean()))
print("Sum of readings:", battery.sum())

pd.DataFrame({"Time_Interval": np.arange(1, 21), "Battery_Percentage": battery}).to_csv("battery.csv", index=False)
print("File saved successfully: battery.csv")

Original battery readings: [13 79 67 47 46 87 13 71 24 14 55 98 75 78 73 80 54 17 85 48]
First: 13 Fifth: 46 Tenth: 14 Last: 48
Below 20%: [13 13 14 17]
Between 30% and 70%: [67 47 46 55 54 48]
Average: 56.2
Minimum: 13 Maximum: 98
Variance: 720.36 Standard deviation: 26.83952309561405
Readings below average: 10
Sum of readings: 1124
File saved successfully: battery.csv


In [7]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(42)
sales = rng.integers(5000, 50001, 30)
updated_sales = sales * 1.05

print("Original sales:", sales)
print("First 7 days:", sales[:7])
print("Last 7 days:", sales[-7:])
print("Sales after 5% increase:", np.round(updated_sales, 2))
print("Above Rs. 30000:", sales[sales > 30000])
print("Between Rs. 15000 and Rs. 25000:", sales[(sales >= 15000) & (sales <= 25000)])
print("Minimum:", sales.min(), "Maximum:", sales.max())
print("Mean:", sales.mean(), "Median:", np.median(sales))
print("Variance:", sales.var(), "Standard deviation:", sales.std())
print("Total monthly sales:", sales.sum())

pd.DataFrame({"Day": np.arange(1, 31), "Original_Sales_Rs": sales,
              "Updated_Sales_Rs": np.round(updated_sales, 2)}).to_csv("sales.csv", index=False)
print("File saved successfully: sales.csv")


Original sales: [ 9016 39828 34456 24749 24486 43637  8867 36382 14066  9238 28692 48903
 38109 39252 37287 40373 28095 10765 42789 25267 27516 21686 13214 46705
 40171 33974 23109 42025 29544 24954]
First 7 days: [ 9016 39828 34456 24749 24486 43637  8867]
Last 7 days: [46705 40171 33974 23109 42025 29544 24954]
Sales after 5% increase: [ 9466.8  41819.4  36178.8  25986.45 25710.3  45818.85  9310.35 38201.1
 14769.3   9699.9  30126.6  51348.15 40014.45 41214.6  39151.35 42391.65
 29499.75 11303.25 44928.45 26530.35 28891.8  22770.3  13874.7  49040.25
 42179.55 35672.7  24264.45 44126.25 31021.2  26201.7 ]
Above Rs. 30000: [39828 34456 43637 36382 48903 38109 39252 37287 40373 42789 46705 40171
 33974 42025]
Between Rs. 15000 and Rs. 25000: [24749 24486 21686 23109 24954]
Minimum: 8867 Maximum: 48903
Mean: 29571.833333333332 Median: 29118.0
Variance: 139042897.27222225 Standard deviation: 11791.645231782639
Total monthly sales: 887155
File saved successfully: sales.csv


In [8]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(42)
speeds = rng.integers(20, 151, 25)

print("Original speed readings:", speeds)
print("First 5:", speeds[:5])
print("Every alternate speed:", speeds[::2])
print("Above 100 km/h:", speeds[speeds > 100])
print("Between 60 and 90 km/h:", speeds[(speeds >= 60) & (speeds <= 90)])
print("Slowest:", speeds.min(), "Fastest:", speeds.max())
print("Average:", speeds.mean(), "Median:", np.median(speeds))
print("Variance:", speeds.var(), "Standard deviation:", speeds.std())
print("Vehicles exceeding 80 km/h:", np.sum(speeds > 80))

pd.DataFrame({"Vehicle": np.arange(1, 26), "Speed_kmh": speeds}).to_csv("vehicle_speed.csv", index=False)
print("File saved successfully: vehicle_speed.csv")

Original speed readings: [ 31 121 105  77  76 132  31 111  46  32  88 147 116 119 113 122  87  36
 130  79  85  68  43 141 122]
First 5: [ 31 121 105  77  76]
Every alternate speed: [ 31 105  76  31  46  88 116 113  87 130  85  43 122]
Above 100 km/h: [121 105 132 111 147 116 119 113 122 130 141 122]
Between 60 and 90 km/h: [77 76 88 87 79 85 68]
Slowest: 31 Fastest: 147
Average: 90.32 Median: 88.0
Variance: 1333.0975999999998 Standard deviation: 36.5116091127192
Vehicles exceeding 80 km/h: 15
File saved successfully: vehicle_speed.csv


In [9]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(42)
orders = rng.integers(100, 2001, 25)
final_orders = orders * 1.05

print("Original order amounts:", orders)
print("First 5:", orders[:5])
print("Last 5:", orders[-5:])
print("Orders after 5% service charge:", np.round(final_orders, 2))
print("Orders above Rs. 1000:", orders[orders > 1000])
print("Orders below Rs. 500:", orders[orders < 500])
print("Minimum:", orders.min(), "Maximum:", orders.max())
print("Mean:", orders.mean(), "Median:", np.median(orders))
print("Variance:", orders.var(), "Standard deviation:", orders.std())
print("Total original revenue:", orders.sum())
print("Customers above average:", np.sum(orders > orders.mean()))

pd.DataFrame({"Order_ID": np.arange(1, 26), "Original_Amount_Rs": orders,
              "Final_Amount_Rs": np.round(final_orders, 2)}).to_csv("restaurant_orders.csv", index=False)
print("File saved successfully: restaurant_orders.csv")


Original order amounts: [ 269 1571 1344  934  923 1732  263 1425  482  279 1100 1954 1498 1546
 1463 1594 1075  343 1696  956 1051  804  447 1861 1585]
First 5: [ 269 1571 1344  934  923]
Last 5: [1051  804  447 1861 1585]
Orders after 5% service charge: [ 282.45 1649.55 1411.2   980.7   969.15 1818.6   276.15 1496.25  506.1
  292.95 1155.   2051.7  1572.9  1623.3  1536.15 1673.7  1128.75  360.15
 1780.8  1003.8  1103.55  844.2   469.35 1954.05 1664.25]
Orders above Rs. 1000: [1571 1344 1732 1425 1100 1954 1498 1546 1463 1594 1075 1696 1051 1861
 1585]
Orders below Rs. 500: [269 263 482 279 343 447]
Minimum: 263 Maximum: 1954
Mean: 1127.8 Median: 1100.0
Variance: 280636.96 Standard deviation: 529.751790936095
Total original revenue: 28195
Customers above average: 12
File saved successfully: restaurant_orders.csv


In [10]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(42)
rainfall = rng.integers(0, 201, 30)

print("Original rainfall data:", rainfall)
print("Days 1 to 10:", rainfall[:10])
print("Final 5 days:", rainfall[-5:])
print("Above 100 mm:", rainfall[rainfall > 100])
print("Below 20 mm:", rainfall[rainfall < 20])
print("Minimum:", rainfall.min(), "Maximum:", rainfall.max())
print("Average:", rainfall.mean(), "Median:", np.median(rainfall))
print("Variance:", rainfall.var(), "Standard deviation:", rainfall.std())
print("Total monthly rainfall:", rainfall.sum())
print("Days above average rainfall:", np.sum(rainfall > rainfall.mean()))

pd.DataFrame({"Day": np.arange(1, 31), "Rainfall_mm": rainfall}).to_csv("rainfall.csv", index=False)
print("File saved successfully: rainfall.csv")


Original rainfall data: [ 17 155 131  88  87 172  17 140  40  18 105 196 147 152 144 157 103  25
 168  90 100  74  36 186 157 129  80 165 109  89]
Days 1 to 10: [ 17 155 131  88  87 172  17 140  40  18]
Final 5 days: [129  80 165 109  89]
Above 100 mm: [155 131 172 140 105 196 147 152 144 157 103 168 186 157 129 165 109]
Below 20 mm: [17 17 18]
Minimum: 17 Maximum: 196
Average: 109.23333333333333 Median: 107.0
Variance: 2780.3122222222223 Standard deviation: 52.72866603871392
Total monthly rainfall: 3277
Days above average rainfall: 14
File saved successfully: rainfall.csv


In [11]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(42)
production = rng.integers(50, 501, (4, 7))

print("Complete 2D array:\n", production)
print("Machine 1 production:", production[0])
print("Day 3 production of all machines:", production[:, 2])
print("Machine 3, Day 5:", production[2, 4])
print("Production values above 300:", production[production > 300])
print("Total for each machine:", production.sum(axis=1))
print("Total for each day:", production.sum(axis=0))
print("Overall minimum:", production.min(), "Overall maximum:", production.max())
print("Overall mean:", production.mean(), "Overall standard deviation:", production.std())
print("Values above overall average:", np.sum(production > production.mean()))

pd.DataFrame(production, index=["Machine_1", "Machine_2", "Machine_3", "Machine_4"],
             columns=[f"Day_{day}" for day in range(1, 8)]).to_csv("factory_production.csv")
print("File saved successfully: factory_production.csv")


Complete 2D array:
 [[ 90 399 345 247 245 437  88]
 [364 140  92 287 490 381 393]
 [373 404 281 107 428 253 275]
 [217 132 467 402 340 231 421]]
Machine 1 production: [ 90 399 345 247 245 437  88]
Day 3 production of all machines: [345  92 281 467]
Machine 3, Day 5: 428
Production values above 300: [399 345 437 364 490 381 393 373 404 428 467 402 340 421]
Total for each machine: [1851 2147 2121 2210]
Total for each day: [1044 1075 1185 1043 1503 1302 1177]
Overall minimum: 88 Overall maximum: 490
Overall mean: 297.4642857142857 Overall standard deviation: 122.05282291546006
Values above overall average: 14
File saved successfully: factory_production.csv


In [12]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(42)
original_data = rng.integers(1, 1001, 50)
after_adding_100 = original_data + 100
final_data = after_adding_100 * 2

print("Original data:", original_data)
print("First 10:", original_data[:10])
print("Last 10:", original_data[-10:])
print("Every second element:", original_data[::2])
print("Indexes 5, 10, 15, 20:", original_data[[5, 10, 15, 20]])
print("After adding 100:", after_adding_100)
print("Final data after multiplying by 2:", final_data)
print("Greater than 500:", original_data[original_data > 500])
print("Between 200 and 600:", original_data[(original_data >= 200) & (original_data <= 600)])
print("Even numbers:", original_data[original_data % 2 == 0])
print("Odd numbers:", original_data[original_data % 2 != 0])
print("Sum:", original_data.sum())
print("Product:", np.prod(original_data, dtype=object))
print("Minimum:", original_data.min(), "Maximum:", original_data.max())
print("Mean:", original_data.mean(), "Median:", np.median(original_data))
print("Variance:", original_data.var(), "Standard deviation:", original_data.std())
print("25th, 50th, 75th percentiles:", np.percentile(original_data, [25, 50, 75]))
print("Count above mean:", np.sum(original_data > original_data.mean()))
print("Ascending sorted data:", np.sort(original_data))

np.save("original_data.npy", original_data)
pd.DataFrame({"Final_Processed_Data": final_data}).to_csv("final_data.csv", index=False)
print("File saved successfully: original_data.npy")
print("File saved successfully: final_data.csv")

Original data: [ 90 774 655 439 434 859  86 698 202  95 527 976 736 762 718 787 514 129
 840 451 501 371 183 927 782 644 403 823 546 444 451 228  93 555 888  64
 859 828 277 632 166 759 701 355  68 971 446 894 678 779]
First 10: [ 90 774 655 439 434 859  86 698 202  95]
Last 10: [166 759 701 355  68 971 446 894 678 779]
Every second element: [ 90 655 434  86 202 527 736 718 514 840 501 183 782 403 546 451  93 888
 859 277 166 701  68 446 678]
Indexes 5, 10, 15, 20: [859 527 787 501]
After adding 100: [ 190  874  755  539  534  959  186  798  302  195  627 1076  836  862
  818  887  614  229  940  551  601  471  283 1027  882  744  503  923
  646  544  551  328  193  655  988  164  959  928  377  732  266  859
  801  455  168 1071  546  994  778  879]
Final data after multiplying by 2: [ 380 1748 1510 1078 1068 1918  372 1596  604  390 1254 2152 1672 1724
 1636 1774 1228  458 1880 1102 1202  942  566 2054 1764 1488 1006 1846
 1292 1088 1102  656  386 1310 1976  328 1918 1856  754 1464  