In [1]:
import numpy as np

marks = np.array([70, 85, 60, 90, 75])

print(marks.mean())


76.0


In [2]:
import pandas as pd

data = {
    'Name': ['Arun', 'Banu', 'Kumar'],
    'Marks': [75, 90, 60]
}

df = pd.DataFrame(data)

print(df)


    Name  Marks
0   Arun     75
1   Banu     90
2  Kumar     60


In [3]:
import numpy as np

marks = np.array([70, 80, 90, 60, 75])

print(marks[0])
print(marks[3])


70
60


In [4]:
print(marks[-1])

75


In [5]:
print(marks[-2])

60


In [7]:
import numpy as np

a = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])


In [8]:
print(a[0, 0])

10


In [9]:
print(a[1, 2])

60


In [10]:
a[2, 1]

np.int64(80)

In [11]:
print(a[1])

[40 50 60]


In [12]:
print(a[:, 1])

[20 50 80]


In [13]:
marks[2]

np.int64(90)

In [14]:
marks[1:4]

array([80, 90, 60])

In [15]:
import numpy as np

fruits = np.array(["Apple", "Mango", "Orange", "Grapes", "Banana"])

print(fruits[0])
print(fruits[2])
print(fruits[-1])


Apple
Orange
Banana


In [17]:
import numpy as np

print(np.random.random())


0.38127310222817


In [18]:
print(np.random.random(5))

[0.36941848 0.08160125 0.25084015 0.8654113  0.33066237]


In [19]:
print(np.random.randint(1, 10))

1


In [20]:
dice = np.random.randint(1, 7)

print("Dice:", dice)


Dice: 3


In [21]:
numbers = np.random.randint(1, 101, 10)

print(numbers)


[85 63 37 48 73 82 61 62 58 43]


In [22]:
students = np.array(["Arun", "Bala", "John", "Priya"])
Select one random student:
winner = np.random.choice(students)

print(winner)


SyntaxError: invalid syntax (3828786715.py, line 2)

In [23]:
students = np.array(["Arun", "Bala", "John", "Priya"])

In [24]:
winner = np.random.choice(students)

print(winner)


John


In [25]:
students = np.array([
    "Arun",
    "Bala",
    "John",
    "Priya",
    "Ravi"
])

print(np.random.choice(students, 2))


['Bala' 'Bala']


In [26]:
numbers = np.array([1, 2, 3, 4, 5])

In [27]:
np.random.shuffle(numbers)

print(numbers)


[1 5 2 3 4]


In [28]:
np.random.seed(42)

In [29]:
np.random.seed(42)

print(np.random.randint(1, 100, 5))


[52 93 15 72 61]


In [30]:
import numpy as np

student_guess = int(input("Guess dice number (1-6): "))

computer = np.random.randint(1, 7)

print("Computer generated:", computer)

if student_guess == computer:
    print("Congratulations! Correct guess.")
else:
    print("Try again!")


Guess dice number (1-6): 3
Computer generated: 5
Try again!


In [32]:
import numpy as np

prices = np.array([100, 200, 300, 400, 500])


In [33]:
import numpy as np

prices = np.array([100, 200, 300, 400, 500])

print(np.mean(prices))


300.0


In [34]:
print(np.median(prices))

300.0


In [35]:
from scipy import stats

data = [10, 20, 20, 20, 30, 40]

print(stats.mode(data))


ModeResult(mode=np.int64(20), count=np.int64(3))


In [36]:
print(np.min(prices))

100


In [37]:
print(np.max(prices))

500


In [38]:
range_value = np.max(prices) - np.min(prices)

print(range_value)


400


In [39]:
data = np.array([10, 30, 50, 70, 90])

print(np.var(data))


800.0


In [40]:
data = np.array([10, 30, 50, 70, 90])

print(np.std(data))


28.284271247461902


In [41]:
print(round(np.std(data), 2))

28.28


In [42]:
print(round(np.std(data), 2))

28.28


In [43]:
print(np.percentile(data, 25))
print(np.percentile(data, 50))
print(np.percentile(data, 75))


30.0
50.0
70.0


In [44]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

print("Data:", data)

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Range:", np.max(data) - np.min(data))
print("Variance:", np.var(data))
print("Standard Deviation:", np.std(data))


Data: [10 20 30 40 50]
Mean: 30.0
Median: 30.0
Minimum: 10
Maximum: 50
Range: 40
Variance: 200.0
Standard Deviation: 14.142135623730951


In [45]:
import numpy as np

marks = np.array([45, 78, 90, 55, 82, 60])

result = marks[marks > 60]

print(result)


[78 90 82]


In [46]:
marks[marks > 70]

array([78, 90, 82])

In [47]:
marks = np.array([45, 78, 90, 55, 82, 60])

In [48]:
marks[marks < 60]

array([45, 55])

In [49]:
marks[marks >= 60]

array([78, 90, 82, 60])

In [50]:
marks[marks == 60]

array([60])

In [51]:
marks[marks != 60]

array([45, 78, 90, 55, 82])

In [52]:
marks = np.array([45, 78, 90, 55, 82, 60, 70])

result = marks[(marks >= 60) & (marks <= 80)]

print(result)


[78 60 70]


In [53]:
result = marks[(marks < 50) | (marks > 80)]

print(result)


[45 90 82]


In [54]:
import numpy as np

colors = np.array(["Red", "Blue", "Red", "Green", "Blue"])

result = colors[colors == "Red"]

print(result)


['Red' 'Red']


In [55]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8])

result = numbers[numbers % 2 == 0]

print(result)


[2 4 6 8]


In [56]:
result = numbers[numbers % 2 != 0]

print(result)


[1 3 5 7]


In [57]:
import numpy as np

prices = np.array([120, 450, 250, 700, 90, 550, 300])


In [58]:
print(prices[prices > 300])

[450 700 550]


In [59]:
print(prices[prices < 200])

[120  90]


In [60]:
print(prices[(prices >= 200) & (prices <= 500)])

[450 250 300]


In [61]:
import numpy as np

sales = np.array([100, 200, 150, 300, 250])

print("Total Sales:", np.sum(sales))
print("Average Sales:", np.mean(sales))
print("Minimum Sales:", np.min(sales))
print("Maximum Sales:", np.max(sales))
print("Number of Records:", sales.size)


Total Sales: 1000
Average Sales: 200.0
Minimum Sales: 100
Maximum Sales: 300
Number of Records: 5


In [63]:
import numpy as np

data = np.array([
    [10, 20, 30],
    [40, 50, 60]
])


In [64]:
print(np.sum(data))

210


In [65]:
print(np.sum(data, axis=0))

[50 70 90]


In [66]:
print(np.sum(data, axis=1))

[ 60 150]


In [67]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(np.mean(data, axis=0))


[25. 35. 45.]


In [68]:
import numpy as np

marks = np.array([70, 80, 90, 60, 75])


In [70]:
import numpy as np

marks = np.array([70, 80, 90, 60, 75])

np.save("marks.npy", marks)

print("Data saved successfully")


Data saved successfully


In [71]:
data = np.load("marks.npy")

print(data)


[70 80 90 60 75]


In [72]:
import numpy as np

marks = np.array([70, 80, 90, 60, 75])

np.savetxt("marks.txt", marks)

print("Saved")


Saved


In [73]:
data = np.loadtxt("marks.txt")

print(data)


[70. 80. 90. 60. 75.]


In [74]:
import numpy as np

data = np.array([
    [101, 75],
    [102, 85],
    [103, 90]
])

np.savetxt("data.csv", data, delimiter=",")


In [75]:
data = np.loadtxt("data.csv", delimiter=",")

print(data)


[[101.  75.]
 [102.  85.]
 [103.  90.]]


In [77]:
import numpy as np

data = np.array([
    [101, 75],
    [102, 85],
    [103, 90]
])

np.savetxt(
    "student_data.csv",
    data,
    delimiter=",",
    fmt="%d",
    header="Student_ID,Mark",
    comments=""
)


In [78]:
import numpy as np

data = np.array([
    [101, 450],
    [102, 700],
    [103, 550],
    [104, 900]
])

# Save as NumPy file
np.save("sales.npy", data)

# Save as CSV file
np.savetxt(
    "sales.csv",
    data,
    delimiter=",",
    fmt="%d",
    header="Product_ID,Sales",
    comments=""
)

print("Data saved successfully")

# Load NumPy file
loaded_data = np.load("sales.npy")

print("Loaded Data:")
print(loaded_data)


Data saved successfully
Loaded Data:
[[101 450]
 [102 700]
 [103 550]
 [104 900]]
