In [1]:
import numpy as np

# XOR Dataset
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y = np.array([
    [0],
    [1],
    [1],
    [0]
])

# Sigmoid Activation Function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of Sigmoid
def sigmoid_derivative(x):
    return x * (1 - x)

# Random Seed
np.random.seed(1)

# Network Architecture
input_neurons = 2
hidden_neurons = 2
output_neurons = 1

# Initialize Weights and Biases
w_hidden = np.random.uniform(size=(input_neurons, hidden_neurons))
b_hidden = np.random.uniform(size=(1, hidden_neurons))

w_output = np.random.uniform(size=(hidden_neurons, output_neurons))
b_output = np.random.uniform(size=(1, output_neurons))

# Hyperparameters
learning_rate = 0.5
epochs = 10000

# Training
for epoch in range(epochs):

    # Forward Propagation
    hidden_input = np.dot(X, w_hidden) + b_hidden
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, w_output) + b_output
    predicted_output = sigmoid(final_input)

    # Error
    error = y - predicted_output

    # Backpropagation
    d_output = error * sigmoid_derivative(predicted_output)

    error_hidden = np.dot(d_output, w_output.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)

    # Update Weights and Biases
    w_output += learning_rate * np.dot(hidden_output.T, d_output)
    b_output += learning_rate * np.sum(d_output, axis=0, keepdims=True)

    w_hidden += learning_rate * np.dot(X.T, d_hidden)
    b_hidden += learning_rate * np.sum(d_hidden, axis=0, keepdims=True)

# -----------------------------
# Testing
# -----------------------------
print("Input Data:")
print(X)

print("\nActual Output:")
print(y)

print("\nPredicted Output:")
print(np.round(predicted_output, 4))

print("\nFinal Classified Output:")
print((predicted_output > 0.5).astype(int))

Input Data:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Actual Output:
[[0]
 [1]
 [1]
 [0]]

Predicted Output:
[[0.0193]
 [0.9833]
 [0.9834]
 [0.0173]]

Final Classified Output:
[[0]
 [1]
 [1]
 [0]]
